version: '3.8'

services:
  api:
    build: ./backend
    container_name: api_c
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - reactapp
  reactapp:
    build: ./frontend
    container_name: reactapp_c
    ports:
      - '3000:3000'
    volumes:
      - ./reactapp:/app
      - /app/node_modules
    stdin_open: true
    tty: true